# Cloudflare Pages configuration

[build]
command = "chmod +x ./build.sh && ./build.sh"
publish = "dist"

[build.environment]
NODE_VERSION = "20"
NPM_VERSION = "9"

# Ensure routes are handled correctly for SPA
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Exclude API routes from SPA redirect
[[redirects]]
from = "/api/*"
to = "/api/:splat"
status = 200

# Specify the entry point for Cloudflare Functions
[functions]
directory = "functions"
node_compat = true

# Environment-specific configurations
[env.production]
name = "production"
NODE_ENV = "production"

[env.preview]
name = "preview"
NODE_ENV = "development"